
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EuroToDhConverterService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EuroToDhConverterService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://example.org/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://example.org/", className = "proxy.GetCompteResponse")
    @Action(input = "http://example.org/EuroToDhConverterService/getCompteRequest", output = "http://example.org/EuroToDhConverterService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion", targetNamespace = "http://example.org/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "conversionResponse", targetNamespace = "http://example.org/", className = "proxy.ConversionResponse")
    @Action(input = "http://example.org/EuroToDhConverterService/conversionRequest", output = "http://example.org/EuroToDhConverterService/conversionResponse")
    public double conversion(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListComptes", targetNamespace = "http://example.org/", className = "proxy.GetListComptes")
    @ResponseWrapper(localName = "getListComptesResponse", targetNamespace = "http://example.org/", className = "proxy.GetListComptesResponse")
    @Action(input = "http://example.org/EuroToDhConverterService/getListComptesRequest", output = "http://example.org/EuroToDhConverterService/getListComptesResponse")
    public List<Compte> getListComptes();

}
